C4Context
    accTitle: App
    accDescr: Containers

    Person(person, "Пользователь", "Пользователь, который использует приложение")

    System_Boundary(App, "Приложение", "Позволяет пользователю следить за питанием") {
        Container(App, "Интерфейс приложения", "Kotlin", "Интерфейс, через который пользователь использует приложение")
        Container(api, "API", "API Gateway", "API, который передает информацию в систему")
        ContainerDb(db, "База данных", "PostgreSQL", "Таблицы, в которых находится информация о пользователях, о блюдах")

        Rel(App, api, "Запросы", "Data")
        Rel(api, db, "Чтение и запись", "Data")
    }

    Rel(person, App, "Использование", "Data")