C4Context
    accTitle: App
    accDescr: Context

    Person(person, "Пользователь", "Пользователь, который использует приложение")

    System(App, "Приложение", "Позволяет пользователю следить за питанием")
    System_Ext(cdp, "Система", "Обрабатывает данные и выводит пользователю результат")
    System(dwh, "DWH", "Хранит данные")

    Rel(person, App, "Ввод данных, просмотр, отправка изображений", "Data")
    Rel(App, dwh, "Данные", "Data")
    Rel(App, cdp, "Запрос пользователя", "Data")
    Rel(dwh, cdp, "Данные", "Data")
    Rel(cdp, person, "Результаты", "Data")